#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'key' : 'value' , 'first_name' : 'brandon', 'last_name' : 'sartele' }
r = requests.post(url, data=payload)

print r.status_code
print r.text


